name: abacatepay_flutter
description: Official Flutter SDK for AbacatePay - PIX Payment Gateway integration
version: 0.0.1
homepage: https://abacatepay.com
repository: https://github.com/AbacatePay/abacatepay-flutter-sdk
issue_tracker: https://github.com/AbacatePay/abacatepay-flutter-sdk/issues
documentation: https://docs.abacatepay.com

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  json_annotation: ^4.8.1
  crypto: ^3.0.3
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
  test: ^1.24.0
  mockito: ^5.4.0
  build_verify: ^3.1.0
  http_mock_adapter: ^0.6.0
  very_good_analysis: ^5.1.0

flutter:
